### ISSUE TITLE
Url not running

### ISSUE THREAD

**Issue by mahesh247** [whizzzkid/instagram-reverse-proxy#6]
There seems to be a problem, its giving following error.
**There's nothing here, yet.**

**Comment by waclock** [comment]
Appearently the heroku app was moved. Having the same issue

**Comment by whizzzkid** [comment]
It's probably because of the sheer number of requests we've been serving, I received an email from heroku this morning that my account had been suspended. Check the hits, probably heroku got mad for bombing their free tier with so many requests.

![Imgur](http://i.imgur.com/pNp7R74.png)

Standing by for response from them. Last I detected https://www.bnk48.com/ was sending in most of these requests. Eventually their website's instagram section is down with this.

**Comment by whizzzkid** [comment]
Everything should now be accessible from https://igpi.ga
